theme: jekyll-theme-minimal
title: Mamoru Yakuwa

navigation:
- title: Home
  url: index.md
- title: Research
  url: Pages/Research.md
- title: Materials
  url: Pages/Materials.md
- title: Contact
  url: Pages/Contact.md
